/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "这里是导航栏",
  "description": "Just playing around",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "../assets/img/logo.jpg",
        "heroText": "这里是主页",
        "tagline": "这里是主页 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-7a719dac",
      "path": "/"
    },
    {
      "title": "默认",
      "frontmatter": {},
      "regularPath": "/foo/",
      "relativePath": "foo/README.md",
      "key": "v-5f3ee5ae",
      "path": "/foo/",
      "headers": [
        {
          "level": 2,
          "title": "1.0",
          "slug": "_1-0"
        },
        {
          "level": 2,
          "title": "2.0",
          "slug": "_2-0"
        }
      ]
    },
    {
      "title": "默认guide",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-543ed486",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "1.0",
          "slug": "_1-0"
        },
        {
          "level": 2,
          "title": "2.0",
          "slug": "_2-0"
        }
      ]
    },
    {
      "title": "第一文档",
      "frontmatter": {},
      "regularPath": "/foo/one.html",
      "relativePath": "foo/one.md",
      "key": "v-1f4fbc84",
      "path": "/foo/one.html"
    },
    {
      "title": "第二文档",
      "frontmatter": {},
      "regularPath": "/foo/two.html",
      "relativePath": "foo/two.md",
      "key": "v-27f5b044",
      "path": "/foo/two.html"
    }
  ],
  "themeConfig": {
    "logo": "/assets/img/logo.jpg",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Guide",
        "link": "/guide/"
      },
      {
        "text": "foo",
        "link": "/foo/"
      },
      {
        "text": "External",
        "link": "https://google.com"
      },
      {
        "text": "工具箱",
        "items": [
          {
            "text": "在线编辑",
            "items": [
              {
                "text": "图片压缩",
                "link": "https://tinypng.com/"
              }
            ]
          },
          {
            "text": "在线服务",
            "items": [
              {
                "text": "阿里云",
                "link": "https://www.aliyun.com/"
              },
              {
                "text": "腾讯云",
                "link": "https://cloud.tencent.com/"
              }
            ]
          },
          {
            "text": "博客指南",
            "items": [
              {
                "text": "掘金",
                "link": "https://juejin.im/"
              },
              {
                "text": "CSDN",
                "link": "https://blog.csdn.net/"
              }
            ]
          }
        ]
      }
    ],
    "sidebar": {
      "/foo/": [
        "",
        "one",
        "two"
      ]
    }
  }
}